apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gaussia-evalhub.fullname" . }}-quickstart
  labels:
    {{- include "gaussia-evalhub.labels" . | nindent 4 }}
data:
  run_quickstart.py: |-
{{ .Files.Get "files/run_quickstart.py" | indent 4 }}
  first-line-support.json: |-
{{ .Files.Get "files/first-line-support.json" | indent 4 }}
  retail.json: |-
{{ .Files.Get "files/retail.json" | indent 4 }}
  root-cause-analysis.json: |-
{{ .Files.Get "files/root-cause-analysis.json" | indent 4 }}
