{{- if and (not .Values.evalhub.existingSecret) .Values.evalhub.authToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gaussia-evalhub.fullname" . }}-evalhub
  labels:
    {{- include "gaussia-evalhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  EVALHUB_AUTH_TOKEN: {{ .Values.evalhub.authToken | quote }}
{{- end }}
