apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gaussia-evalhub.fullname" . }}-quickstart
  labels:
    {{- include "gaussia-evalhub.labels" . | nindent 4 }}
data:
  run_quickstart.py: |-
{{ .Files.Get "files/run_quickstart.py" | indent 4 }}
  agent_transcript_short.json: |-
{{ .Files.Get "files/agent_transcript_short.json" | indent 4 }}
  agent_transcript_long.json: |-
{{ .Files.Get "files/agent_transcript_long.json" | indent 4 }}
