{{- if and .Values.mlflow.create (not .Values.job.enabled) }}
apiVersion: mlflow.opendatahub.io/v1
kind: MLflow
metadata:
  name: {{ .Values.mlflow.serviceName }}
  namespace: redhat-ods-applications
spec:
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.mlflow.storage.size }}
  backendStoreUri: {{ .Values.mlflow.storage.backendStoreUri }}
  artifactsDestination: {{ .Values.mlflow.storage.artifactsDestination }}
  serveArtifacts: {{ .Values.mlflow.storage.serveArtifacts }}
{{- end }}