{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gaussia-evalhub.serviceAccountName" . }}
  labels:
    {{- include "gaussia-evalhub.labels" . | nindent 4 }}
{{- end }}
