apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gaussia-ui
    app.kubernetes.io/component: gaussia-ui
    app.kubernetes.io/instance: gaussia-ui
  name: gaussia-ui
  namespace: gaussia-evalhub-quickstart
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: gaussia-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        deployment: gaussia-ui
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: Always
        name: gaussia-ui
        ports:
        - containerPort: 8501
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: ocp-api-edit
      serviceAccountName: ocp-api-edit
      terminationGracePeriodSeconds: 30