{{- if and .Values.ui.enabled .Values.ui.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "gaussia-evalhub.uiName" . }}-edit
  labels:
    {{- include "gaussia-evalhub.uiLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - kind: ServiceAccount
    name: {{ include "gaussia-evalhub.uiServiceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
