{{- if and .Values.ui.enabled .Values.ui.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "gaussia-evalhub.uiName" . }}
  labels:
    {{- include "gaussia-evalhub.uiLabels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "gaussia-evalhub.uiName" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
{{- end }}
